### ISSUE TITLE
1440p channel list section is glitching

### ISSUE THREAD

**Issue by M0n7y5** [PatrykBielanin/discord-cyberpunk2077-theme#1]
If you have 1440p monitor and you have maximized window with your skin enabled then scrolling is glitching.
This is happening only when scrolling to bottom. It also causes channels not be clickable.

**Comment by PatrykBielanin** [comment]
Sorry for keep you waiting but here i come with feedback.

Latest update should fix jumping scroll. Unfortunatellly i was forced to minimalize margin between channels name divs because discord generate whole div height based on their default css styles and adding extra space causes scroll to jump in certain spots (mostly when there's lots of channels). To be sure i checked some other themes where people also changed margins and paddings and they have the same problem. I hope you'll still enjoy this theme even with smaller gaps between channels divs. Let me know if it's working for you now.

**Comment by M0n7y5** [comment]
I'll check if it's fixed asap

**Comment by M0n7y5** [comment]
Its fixed thx!
