### ISSUE TITLE
It doesn't work!

### ISSUE THREAD

**Issue by shadkz** [PatrykBielanin/discord-cyberpunk2077-theme#9]
Hi, today i started discord like every day and your theme is not working :(.
I tried with different themes, and they work fine.

What happened?
U have an awesome theme!

**Comment by PatrykBielanin** [comment]
Hi, my theme broke because discord pushed out massive update today. Im gonna look into this and will fix it but i need time to do it. Please be patient, i will leave a comment here when its done 👌

Note from better discord developers

> Discord just pushed out a massive rework of all their internals. Expect all themes and pretty much all plugins and even BD itself to break.

> Updates for BD will happen as soon as I have time. Plugin and theme updates will be dependent on the individual developers.


Im glad you like my theme, hopefully i can look into it asap 😊

**Comment by PatrykBielanin** [comment]
Unfortunately i'm not even able to work on this issue because my discord crashes right after launching devtools mode. I need them to check new css classes names to style my theme. I want to fix asap but im not even able to run needed tools. Please stay patient, i reached out to better discord devs to find any solution to this problem.

Here's a video how it works right now 🫤

https://github.com/PatrykBielanin/discord-cyberpunk2077-theme/assets/55627799/5e277c0d-a779-4cfc-87fc-83e3ec0d274a

**Comment by AngelGonePro** [comment]
Yea, it's been like this since the new Discord update. Vencord had to fix their plugins and code because of it.

**Comment by shadkz** [comment]
Yep.. well if u need some help, let me know.

**Comment by moth-boi** [comment]
@PatrykBielanin okay so what I found out that's only issue on windows cause of some electron bullshit. Essentially opening dev tools goes over 2GB limit and crashes the discord. I found workaround by first pressing `Ctrl + R` to reload and immediately pressing `Ctrl + Shift + I`

**Comment by PatrykBielanin** [comment]
@moth-boi Thank you, this workaround really works 👌 Now i will start fixing my theme and hopefully drop update this evening.

**Comment by PatrykBielanin** [comment]
I just released update with fixes to the most important things like chat, channels list, servers list, in-game activity etc. There's still some job to do like popups with emojis, stickers etc. but i dont really have that much time to spend on it (private stuff + work). I will definitely fix them sooner or later 😊 I leave this thread open to let you know when everything will be ready. If anyone wants to help then feel free to contribute 👍

**Comment by angsaysroar** [comment]
Is there away to change the font size used for posts?

**Comment by PatrykBielanin** [comment]
Fixed with #16
